name: Delete merged branch

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: SvanBoxel/delete-merged-branch@v1.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}